apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::427665145658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5HTWOCA2NSQ8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::427665145658:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-11T11:00:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3122"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 20bdbf69-0900-4665-8306-a264ba74b697
